baseurl: "http://swebber.me/"
title: "SWebber IT Services"
languageCode: "en-us"
contentdir: "src/content"
datadir: "src/data"
layoutdir: "src/layouts"
publishdir: "dist"
staticdir: "src/static"
themesdir: "src/themes"
canonifyurls: false

permalinks:
    blog: "/blog/:year/:month/:day/:filename/"


params:
    blog_description: "**DBA**, Consultor, Instrutor, [aprendiz de] **Ninja** e **metido a Chef** nas horas vagas!"
    blog_title: "Blog do Seba"
    blog_author: "Sebastian Webber"
    github_user: "sebastianwebber"

taxonomies:
  tag: "tags"
  category: "categories"
  series: "series"