baseurl: "http://swebber.me/"
title: "Blog do Seba"
languageCode: "en-us"
contentdir: "src/content"
datadir: "src/data"
layoutdir: "src/layouts"
publishdir: "dist"
staticdir: "src/static"
themesdir: "src/themes"
canonifyurls: false

permalinks:
    blog: "/blog/:year/:month/:day/:filename/"

languageCode: "en-us"
copyright: "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."

author:
    name: "Sebastian Webber"
    email: "sebastian@swebber.me"

params:
    blog_description: "**DBA**, Consultor, Instrutor, [aprendiz de] **Ninja** e **metido a Chef** nas horas vagas!"
    blog_title: title
    blog_author: author.name
    github_user: "sebastianwebber"
    twitter_user: "sebastian_swc"
    instagram_user: "_sebastianwebber"

taxonomies:
  tag: "tags"
  category: "categories"
  series: "series"
